#ifndef _BACNET_CONFIG_H_
#define _BACNET_CONFIG_H_

#define BACNET_VENDOR_ID 1000
#define BACNET_VENDOR_NAME "YunSu Electric"

#define MAX_TSM_TRANSACTIONS 0

// #define PRINT_ENABLED_RECEIVE
#define PRINT_ENABLED_RECEIVE_DATA
#define PRINT_ENABLED_RECEIVE_ERRORS
// #define PRINT_ENABLED_MASTER

#endif